name: CI


on:
 
  push:
    branches: [ main ]
  

  


jobs:
  
  build:
    
    runs-on: self-hosted

      

   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello!

      - name: Current pwd
        run: |
           pwd & ls -l
           echo "$usr/bin" >> $GITHUB_PATH
          
      - name: Copy data to Absulate path    
        run: |
           cp -r /usr/bin/HOME/src/Testrunner/Testrunner/README.md "$GITHUB_PATH"/HOME/src
           pwd
           ls -lrt
