name: CI


on:
 
  push:
    branches: [ main ]
  

  


jobs:
  
  build:
  
  
    
    runs-on: self-hosted

      

   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello!

      - name: Current pwd
        run: |
           pwd & ls -l
           export PATH="/usr/bin:$PATH"
#           echo "$usr/bin" >> $GITHUB_VARIABLE
#           echo "$GITHUB_VARIABLE"
          
      - name: Copy data to Absulate path    
        run: |
           cd /usr/bin/   
           cp -r $PATH/HOME/src/Testrunner/Testrunner/README.md $PATH/HOME/src
           pwd
           ls -lrt
#           cp -r ./HOME/src/Testrunner/Testrunner/README.md ./HOME/src
           
